### ISSUE TITLE
Wrong argument name

### ISSUE THREAD

**Issue by iamjexcdevvv** [Mergevos/samp-vehicle-framework#48]
There is a mistakes on your code on line 1792 its supposed to be IsValidVehicle(vehicleid) not IsValidVehicle(id)

vehicle_plus.inc(1792) : error 017: undefined symbol "id"; did you mean "I@"?

**Comment by iamjexcdevvv** [comment]
Also I just wanna report this warning after compiling can you also please fix this? cuz its annoying btw that's all for now, I'll create additional issue if I found some bugs or errors again

warning 203: symbol is never used: "_yT@__Vehicle_DistanceTravelled"
warning 203: symbol is never used: "_yT@__Vehicle_HealthTrack"

**Comment by Mergevos** [comment]
> Also I just wanna report this warning after compiling can you also please fix this? cuz its annoying btw that's all for now, I'll create additional issue if I found some bugs or errors again
> 
> warning 203: symbol is never used: "_yT@__Vehicle_DistanceTravelled" warning 203: symbol is never used: "_yT@__Vehicle_HealthTrack"

Open separate issue for this.
