### ISSUE TITLE
spawning exact vehicle model ?

### ISSUE THREAD

**Issue by ExileFox** [Mergevos/samp-vehicle-framework#57]
On sa-mp 0.3x i recall issues with having no control over which variant is spawning.

I asked on the sa-mp discord if there was any way to control this but that thread has remained unanswered for 2 weeks.

Specifically, the ZR350 may spawn with a rear spoiler, or it may not, it's random.
There are a handful of vehicles that have this feature but none-the-less I'd like to have control over this.

**Comment by Mergevos** [comment]
I think there is no real way or I'm unaware of one which determines what vehicle to spawn.

**Comment by ExileFox** [comment]
alright. thanks anyway. Closing for now.
